package com.example.ajinafro.utils;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import com.example.ajinafro.R;
import com.example.ajinafro.adapters.CitiesAdapter;
import com.example.ajinafro.models.City;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.widget.EditText;

import java.util.ArrayList;

import butterknife.BindView;
import butterknife.ButterKnife;
import butterknife.OnClick;
import butterknife.OnTextChanged;

public class CityPickerActivity extends AppCompatActivity {

    private static final String TAG = "CityPickerActivity";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_city_picker);
        ButterKnife.bind(this);

        loadCities();
        cityname_Field.setHint(getIntent().getStringExtra("initialCity"));
        selectedCity=getIntent().getStringExtra("initialCity");

        LinearLayoutManager linearLayoutManager = new LinearLayoutManager(this);
        citypicker_recycleview.setLayoutManager(linearLayoutManager);
        VerticalSpacingItemDecorator itemDecorator = new VerticalSpacingItemDecorator(25);
        citypicker_recycleview.addItemDecoration(itemDecorator);
        CitiesAdapter cities_adapter=new CitiesAdapter(getApplicationContext(), (ArrayList<City>) cities,this);
        citypicker_recycleview.setAdapter(cities_adapter);
    }
    ArrayList<City> cities;
    public String selectedCity;
    public void setSelectedCity(String selectedCity){
        this.selectedCity=selectedCity;
    }

    @BindView(R.id.citypicker_cityname)
    EditText cityname_Field;

    @OnTextChanged(R.id.citypicker_cityname)
    void searchRestaurantByName(){
        String city_search_field=cityname_Field.getText().toString().toLowerCase().trim();
        ArrayList<City>cities_match_search = new ArrayList<>();
        for(int i=0;i<cities.size();i++){
            if(cities.get(i).getName().toLowerCase().contains(city_search_field)){
                cities_match_search.add(cities.get(i));
            }
        }
        CitiesAdapter restaurantAdapter=new CitiesAdapter(getApplicationContext(),cities_match_search, this);
        citypicker_recycleview.setAdapter(restaurantAdapter);
    }

    @OnClick(R.id.citypicker_confirme_btn)
    void sendResult(){
        if(selectedCity!=null){
            Intent returnIntent = new Intent();
            returnIntent.putExtra("selectedCity",selectedCity);
            setResult(Activity.RESULT_OK,returnIntent);
            finish();
        }else{
            Intent returnIntent = new Intent();
            setResult(Activity.RESULT_CANCELED,returnIntent);
            finish();
        }
    }

    @BindView(R.id.citypicker_recycleview)
    RecyclerView citypicker_recycleview;
    @OnClick(R.id.back_button)
    void back_to(){
    onBackPressed();
}
    void loadCities(){
        cities=new ArrayList<City>();
        cities.add(new City(1, "Aïn Harrouda", 6));
        cities.add(new City(2, "Ben Yakhlef", 6));
        cities.add(new City(3, "Bouskoura", 6));
        cities.add(new City(4, "Casablanca", 6));
        cities.add(new City(5, "Médiouna", 6));
        cities.add(new City(6, "Mohammadia", 6));
        cities.add(new City(7, "Tit Mellil", 6));
        cities.add(new City(8, "Ben Yakhlef", 6));
        cities.add(new City(9, "Bejaâd", 5));
        cities.add(new City(10, "Ben Ahmed", 6));
        cities.add(new City(11, "Benslimane", 6));
        cities.add(new City(12, "Berrechid", 6));
        cities.add(new City(13, "Boujniba", 5));
        cities.add(new City(14, "Boulanouare", 5));
        cities.add(new City(15, "Bouznika", 6));
        cities.add(new City(16, "Deroua", 6));
        cities.add(new City(17, "El Borouj", 6));
        cities.add(new City(18, "El Gara", 6));
        cities.add(new City(19, "Guisser", 6));
        cities.add(new City(20, "Hattane", 5));
        cities.add(new City(21, "Khouribga", 5));
        cities.add(new City(22, "Loulad", 6));
        cities.add(new City(23, "Oued Zem", 5));
        cities.add(new City(24, "Oulad Abbou", 6));
        cities.add(new City(25, "Oulad H'Riz Sahel", 6));
        cities.add(new City(26, "Oulad M'rah", 6));
        cities.add(new City(27, "Oulad Saïd", 6));
        cities.add(new City(28, "Oulad Sidi Ben Daoud", 6));
        cities.add(new City(29, "Ras El Aïn", 6));
        cities.add(new City(30, "Settat", 6));
        cities.add(new City(31, "Sidi Rahhal Chataï", 6));
        cities.add(new City(32, "Soualem", 6));
        cities.add(new City(33, "Azemmour", 6));
        cities.add(new City(34, "Bir Jdid", 6));
        cities.add(new City(35, "Bouguedra", 7));
        cities.add(new City(36, "Echemmaia", 7));
        cities.add(new City(37, "El Jadida", 6));
        cities.add(new City(38, "Hrara", 7));
        cities.add(new City(39, "Ighoud", 7));
        cities.add(new City(40, "Jamâat Shaim", 7));
        cities.add(new City(41, "Jorf Lasfar", 6));
        cities.add(new City(42, "Khemis Zemamra", 6));
        cities.add(new City(43, "Laaounate", 6));
        cities.add(new City(44, "Moulay Abdallah", 6));
        cities.add(new City(45, "Oualidia", 6));
        cities.add(new City(46, "Oulad Amrane", 6));
        cities.add(new City(47, "Oulad Frej", 6));
        cities.add(new City(48, "Oulad Ghadbane", 6));
        cities.add(new City(49, "Safi", 7));
        cities.add(new City(50, "Sebt El Maârif", 6));
        cities.add(new City(51, "Sebt Gzoula", 7));
        cities.add(new City(52, "Sidi Ahmed", 7));
        cities.add(new City(53, "Sidi Ali Ban Hamdouche", 6));
        cities.add(new City(54, "Sidi Bennour", 6));
        cities.add(new City(55, "Sidi Bouzid", 6));
        cities.add(new City(56, "Sidi Smaïl", 6));
        cities.add(new City(57, "Youssoufia", 7));
        cities.add(new City(58, "Fès", 3));
        cities.add(new City(59, "Aïn Cheggag", 3));
        cities.add(new City(60, "Bhalil", 3));
        cities.add(new City(61, "Boulemane", 3));
        cities.add(new City(62, "El Menzel", 3));
        cities.add(new City(63, "Guigou", 3));
        cities.add(new City(64, "Imouzzer Kandar", 3));
        cities.add(new City(65, "Imouzzer Marmoucha", 3));
        cities.add(new City(66, "Missour", 3));
        cities.add(new City(67, "Moulay Yaâcoub", 3));
        cities.add(new City(68, "Ouled Tayeb", 3));
        cities.add(new City(69, "Outat El Haj", 3));
        cities.add(new City(70, "Ribate El Kheir", 3));
        cities.add(new City(71, "Séfrou", 3));
        cities.add(new City(72, "Skhinate", 3));
        cities.add(new City(73, "Tafajight", 3));
        cities.add(new City(74, "Arbaoua", 4));
        cities.add(new City(75, "Aïn Dorij", 1));
        cities.add(new City(76, "Dar Gueddari", 4));
        cities.add(new City(77, "Had Kourt", 4));
        cities.add(new City(78, "Jorf El Melha", 4));
        cities.add(new City(79, "Kénitra", 4));
        cities.add(new City(80, "Khenichet", 4));
        cities.add(new City(81, "Lalla Mimouna", 4));
        cities.add(new City(82, "Mechra Bel Ksiri", 4));
        cities.add(new City(83, "Mehdia", 4));
        cities.add(new City(84, "Moulay Bousselham", 4));
        cities.add(new City(85, "Sidi Allal Tazi", 4));
        cities.add(new City(86, "Sidi Kacem", 4));
        cities.add(new City(87, "Sidi Slimane", 4));
        cities.add(new City(88, "Sidi Taibi", 4));
        cities.add(new City(89, "Sidi Yahya El Gharb", 4));
        cities.add(new City(90, "Souk El Arbaa", 4));
        cities.add(new City(91, "Akka", 9));
        cities.add(new City(92, "Assa", 10));
        cities.add(new City(93, "Bouizakarne", 10));
        cities.add(new City(94, "El Ouatia", 10));
        cities.add(new City(95, "Es-Semara", 11));
        cities.add(new City(96, "Fam El Hisn", 9));
        cities.add(new City(97, "Foum Zguid", 9));
        cities.add(new City(98, "Guelmim", 10));
        cities.add(new City(99, "Taghjijt", 10));
        cities.add(new City(100, "Tan-Tan", 10));
        cities.add(new City(101, "Tata", 9));
        cities.add(new City(102, "Zag", 10));
        cities.add(new City(103, "Marrakech", 7));
        cities.add(new City(104, "Ait Daoud", 7));
        cities.add(new City(115, "Amizmiz", 7));
        cities.add(new City(116, "Assahrij", 7));
        cities.add(new City(117, "Aït Ourir", 7));
        cities.add(new City(118, "Ben Guerir", 7));
        cities.add(new City(119, "Chichaoua", 7));
        cities.add(new City(120, "El Hanchane", 7));
        cities.add(new City(121, "El Kelaâ des Sraghna", 7));
        cities.add(new City(122, "Essaouira", 7));
        cities.add(new City(123, "Fraïta", 7));

        cities.add(new City(124, "Ghmate", 7));
        cities.add(new City(125, "Ighounane", 8));
        cities.add(new City(126, "Imintanoute", 7));
        cities.add(new City(127, "Kattara", 7));
        cities.add(new City(128, "Lalla Takerkoust", 7));
        cities.add(new City(129, "Loudaya", 7));
        cities.add(new City(130, "Lâattaouia", 7));
        cities.add(new City(131, "Moulay Brahim", 7));
        cities.add(new City(132, "Mzouda", 7));
        cities.add(new City(133, "Ounagha", 7));
        cities.add(new City(134, "Sid L'Mokhtar", 7));
        cities.add(new City(135, "Sid Zouin", 7));
        cities.add(new City(136, "Sidi Abdallah Ghiat", 7));
        cities.add(new City(137, "Sidi Bou Othmane", 7));
        cities.add(new City(138, "Sidi Rahhal", 7));
        cities.add(new City(139, "Skhour Rehamna", 7));
        cities.add(new City(140, "Smimou", 7));
        cities.add(new City(141, "Tafetachte", 7));
        cities.add(new City(142, "Tahannaout", 7));
        cities.add(new City(143, "Talmest", 7));
        cities.add(new City(144, "Tamallalt", 7));
        cities.add(new City(145, "Tamanar", 7));
        cities.add(new City(146, "Tamansourt", 7));
        cities.add(new City(147, "Tameslouht",7));
        cities.add(new City(148, "Tanalt", 9));
        cities.add(new City(149, "Zeubelemok", 7));
        cities.add(new City(150, "Meknès", 3));
        cities.add(new City(151, "Khénifra", 5));
        cities.add(new City(152, "Agourai", 3));
        cities.add(new City(153, "Ain Taoujdate", 3));
        cities.add(new City(154, "MyAliCherif", 8));
        cities.add(new City(155, "Rissani", 8));
        cities.add(new City(156, "Amalou Ighriben", 5));
        cities.add(new City(157, "Aoufous",8)) ;
        cities.add(new City(158, "Arfoud", 8));
        cities.add(new City(159, "Azrou", 3));
        cities.add(new City(160, "Aïn Jemaa", 3));
        cities.add(new City(161, "Aïn Karma", 3));
        cities.add(new City(162, "Aïn Leuh", 3));
        cities.add(new City(163, "Aït Boubidmane", 3));
        cities.add(new City(164, "Aït Ishaq", 5));
        cities.add(new City(165, "Boudnib", 8));
        cities.add(new City(166, "Boufakrane", 3));
        cities.add(new City(167, "Boumia", 8));
        cities.add(new City(168, "El Hajeb", 3));
        cities.add(new City(169, "Elkbab", 5));
        cities.add(new City(170, "Er-Rich", 5));
        cities.add(new City(171, "Errachidia", 8));
        cities.add(new City(172, "Gardmit", 8));
        cities.add(new City(173, "Goulmima", 8));
        cities.add(new City(174, "Gourrama", 8));
        cities.add(new City(175, "Had Bouhssoussen", 5));
        cities.add(new City(176, "Haj Kaddour", 3));
        cities.add(new City(177, "Ifrane", 3));
        cities.add(new City(178, "Itzer", 8));
        cities.add(new City(179, "Jorf", 8));
        cities.add(new City(180, "Kehf Nsour", 5));
        cities.add(new City(181, "Kerrouchen", 5));
        cities.add(new City(182, "M'haya", 3));
        cities.add(new City(183, "M'rirt", 5));
        cities.add(new City(184, "Midelt", 8));
        cities.add(new City(185, "Moulay Ali Cherif", 8));
        cities.add(new City(186, "Moulay Bouazza", 5));
        cities.add(new City(187, "Moulay Idriss Zerhoun", 3));
        cities.add(new City(188, "Moussaoua", 3));
        cities.add(new City(189, "N'Zalat Bni Amar", 3));
        cities.add(new City(190, "Ouaoumana", 5));
        cities.add(new City(191, "Oued Ifrane", 3));
        cities.add(new City(192, "Sabaa Aiyoun", 3));
        cities.add(new City(193, "Sebt Jahjouh", 3));
        cities.add(new City(194, "Sidi Addi", 3));
        cities.add(new City(195, "Tichoute", 8));
        cities.add(new City(196, "Tighassaline", 5));
        cities.add(new City(197, "Tighza", 5));
        cities.add(new City(198, "Timahdite", 3));
        cities.add(new City(199, "Tinejdad", 8));
        cities.add(new City(200, "Tizguite", 3));
        cities.add(new City(201, "Toulal", 3));
        cities.add(new City(202, "Tounfite", 8));
        cities.add(new City(203, "Zaouia d'Ifrane", 3));
        cities.add(new City(204, "Zaïda", 8));
        cities.add(new City(205, "Ahfir", 2));
        cities.add(new City(206, "Aklim", 2));
        cities.add(new City(207, "Al Aroui", 2));
        cities.add(new City(208, "Aïn Bni Mathar", 2));
        cities.add(new City(209, "Aïn Erreggada", 2));
        cities.add(new City(210, "Ben Taïeb", 2));
        cities.add(new City(211, "Berkane", 2));
        cities.add(new City(212, "Bni Ansar", 2));
        cities.add(new City(213, "Bni Chiker", 2));
        cities.add(new City(214, "Bni Drar", 2));
        cities.add(new City(215, "Bni Tadjite", 2));
        cities.add(new City(216, "Bouanane", 2));
        cities.add(new City(217, "Bouarfa", 2));
        cities.add(new City(218, "Bouhdila", 2));
        cities.add(new City(219, "Dar El Kebdani", 2));
        cities.add(new City(220, "Debdou", 2));
        cities.add(new City(221, "Douar Kannine", 2));
        cities.add(new City(222, "Driouch", 2));
        cities.add(new City(223, "El Aïoun Sidi Mellouk", 2));
        cities.add(new City(224, "Farkhana", 2));
        cities.add(new City(225, "Figuig", 2));
        cities.add(new City(226, "Ihddaden", 2));
        cities.add(new City(227, "Jaâdar", 2));
        cities.add(new City(228, "Jerada", 2));
        cities.add(new City(229, "Kariat Arekmane", 2));
        cities.add(new City(230, "Kassita", 2));
        cities.add(new City(231, "Kerouna", 2));
        cities.add(new City(232, "Laâtamna", 2));
        cities.add(new City(233, "Madagh", 2));
        cities.add(new City(234, "Midar", 2));
        cities.add(new City(235, "Nador", 2));
        cities.add(new City(236, "Naima", 2));
        cities.add(new City(237, "Oued Heimer", 2));
        cities.add(new City(238, "Oujda", 2));
        cities.add(new City(239, "Ras El Ma", 2));
        cities.add(new City(240, "Saïdia", 2));
        cities.add(new City(241, "Selouane", 2));
        cities.add(new City(242, "Sidi Boubker", 2));
        cities.add(new City(243, "Sidi Slimane Echcharaa", 2));
        cities.add(new City(244, "Talsint", 2));
        cities.add(new City(245, "Taourirt", 2));
        cities.add(new City(246, "Tendrara", 2));
        cities.add(new City(247, "Tiztoutine", 2));
        cities.add(new City(248, "Touima", 2));
        cities.add(new City(249, "Touissit", 2));
        cities.add(new City(250, "Zaïo", 2));
        cities.add(new City(251, "Zeghanghane", 2));
        cities.add(new City(252, "Rabat", 4));
        cities.add(new City(253, "Salé", 4));
        cities.add(new City(254, "Ain El Aouda", 4));
        cities.add(new City(255, "Harhoura", 4));
        cities.add(new City(256, "Khémisset", 4));
        cities.add(new City(257, "Oulmès", 4));
        cities.add(new City(258, "Rommani", 4));
        cities.add(new City(259, "Sidi Allal El Bahraoui", 4));
        cities.add(new City(260, "Sidi Bouknadel", 4));
        cities.add(new City(261, "Skhirate", 4));
        cities.add(new City(262, "Tamesna", 4));
        cities.add(new City(263, "Témara", 4));
        cities.add(new City(264, "Tiddas", 4));
        cities.add(new City(265, "Tiflet", 4));
        cities.add(new City(266, "Touarga", 4));
        cities.add(new City(267, "Agadir", 9));
        cities.add(new City(268, "Agdz", 8));
        cities.add(new City(269, "Agni Izimmer", 9));
        cities.add(new City(270, "Aït Melloul", 9));
        cities.add(new City(271, "Alnif", 8));
        cities.add(new City(272, "Anzi", 9));
        cities.add(new City(273, "Aoulouz", 9));
        cities.add(new City(274, "Aourir", 9));
        cities.add(new City(275, "Arazane", 9));
        cities.add(new City(276, "Aït Baha", 9));
        cities.add(new City(277, "Aït Iaâza", 9));
        cities.add(new City(278, "Aït Yalla", 8));
        cities.add(new City(279, "Ben Sergao", 9));
        cities.add(new City(280, "Biougra", 9));
        cities.add(new City(281, "Boumalne-Dadès", 8));
        cities.add(new City(282, "Dcheira El Jihadia", 9));
        cities.add(new City(283, "Drargua", 9));
        cities.add(new City(284, "El Guerdane", 9));
        cities.add(new City(285, "Harte Lyamine", 8));
        cities.add(new City(286, "Ida Ougnidif", 9));
        cities.add(new City(287, "Ifri", 8));
        cities.add(new City(288, "Igdamen", 9));
        cities.add(new City(289, "Ighil n'Oumgoun", 8));
        cities.add(new City(290, "Imassine", 8));
        cities.add(new City(291, "Inezgane", 9));
        cities.add(new City(292, "Irherm", 9));
        cities.add(new City(293, "Kelaat-M'Gouna", 8));
        cities.add(new City(294, "Lakhsas", 9));
        cities.add(new City(295, "Lakhsass", 9));
        cities.add(new City(296, "Lqliâa", 9));
        cities.add(new City(297, "M'semrir", 8));
        cities.add(new City(298, "Massa cities.add(new City(Maroc)", 9));
        cities.add(new City(299, "Megousse", 9));
        cities.add(new City(300, "Ouarzazate", 8));
        cities.add(new City(301, "Oulad Berhil", 9));
        cities.add(new City(302, "Oulad Teïma", 9));
        cities.add(new City(303, "Sarghine", 8));
        cities.add(new City(304, "Sidi Ifni", 10));
        cities.add(new City(305, "Skoura", 8));
        cities.add(new City(306, "Tabounte", 8));
        cities.add(new City(307, "Tafraout", 9));
        cities.add(new City(308, "Taghzout", 1));
        cities.add(new City(309, "Tagzen", 9));
        cities.add(new City(310, "Taliouine", 9));
        cities.add(new City(311, "Tamegroute", 8));
        cities.add(new City(312, "Tamraght", 9));
        cities.add(new City(313, "Tanoumrite Nkob Zagora", 8));
        cities.add(new City(314, "Taourirt ait zaghar", 8));
        cities.add(new City(315, "Taroudannt", 9));
        cities.add(new City(316, "Temsia", 9));
        cities.add(new City(317, "Tifnit", 9));
        cities.add(new City(318, "Tisgdal", 9));
        cities.add(new City(319, "Tiznit", 9));
        cities.add(new City(320, "Toundoute", 8));
        cities.add(new City(321, "Zagora", 8));
        cities.add(new City(322, "Afourar", 5));
        cities.add(new City(323, "Aghbala", 5));
        cities.add(new City(324, "Azilal", 5));
        cities.add(new City(325, "Aït Majden", 5));
        cities.add(new City(326, "Beni Ayat", 5));
        cities.add(new City(327, "Béni Mellal", 5));
        cities.add(new City(328, "Bin elouidane", 5));
        cities.add(new City(329, "Bradia", 5));
        cities.add(new City(330, "Bzou", 5));
        cities.add(new City(331, "Dar Oulad Zidouh", 5));
        cities.add(new City(332, "Demnate", 5));
        cities.add(new City(333, "Dra'a", 8));
        cities.add(new City(334, "El Ksiba", 5));
        cities.add(new City(335, "Foum Jamaa", 5));
        cities.add(new City(336, "Fquih Ben Salah", 5));
        cities.add(new City(337, "Kasba Tadla", 5));
        cities.add(new City(338, "Ouaouizeght", 5));
        cities.add(new City(339, "Oulad Ayad", 5));
        cities.add(new City(340, "Oulad M'Barek", 5));
        cities.add(new City(341, "Oulad Yaich", 5));
        cities.add(new City(342, "Sidi Jaber", 5));
        cities.add(new City(343, "Souk Sebt Oulad Nemma", 5));
        cities.add(new City(344, "Zaouïat Cheikh", 5));
        cities.add(new City(345, "Tanger", 1));
        cities.add(new City(346, "Tétouan", 1));
        cities.add(new City(347, "Akchour", 1));
        cities.add(new City(348, "Assilah", 1));
        cities.add(new City(349, "Bab Berred", 1));
        cities.add(new City(350, "Bab Taza", 1));
        cities.add(new City(351, "Brikcha", 1));
        cities.add(new City(352, "Chefchaouen", 1));
        cities.add(new City(353, "Dar Bni Karrich", 1));
        cities.add(new City(354, "Dar Chaoui", 1));
        cities.add(new City(355, "Fnideq", 1));
        cities.add(new City(356, "Gueznaia", 1));
        cities.add(new City(357, "Jebha", 1));
        cities.add(new City(358, "Karia", 3));
        cities.add(new City(359, "Khémis Sahel", 1));
        cities.add(new City(360, "Ksar El Kébir", 1));
        cities.add(new City(361, "Larache", 1));
        cities.add(new City(362, "M'diq", 1));
        cities.add(new City(363, "Martil", 1));
        cities.add(new City(364, "Moqrisset", 1));
        cities.add(new City(365, "Oued Laou", 1));
        cities.add(new City(366, "Oued Rmel", 1));
        cities.add(new City(367, "Ouazzane", 1));
        cities.add(new City(368, "Point Cires", 1));
        cities.add(new City(369, "Sidi Lyamani", 1));
        cities.add(new City(370, "Sidi Mohamed ben Abdallah el-Raisuni", 1));
        cities.add(new City(371, "Zinat", 1));
        cities.add(new City(372, "Ajdir", 1));
        cities.add(new City(373, "Aknoul", 3));
        cities.add(new City(374, "Al Hoceïma", 1));
        cities.add(new City(375, "Aït Hichem", 1));
        cities.add(new City(376, "Bni Bouayach", 1));
        cities.add(new City(377, "Bni Hadifa", 1));
        cities.add(new City(378, "Ghafsai", 3));
        cities.add(new City(379, "Guercif", 2));
        cities.add(new City(380, "Imzouren", 1));
        cities.add(new City(381, "Inahnahen", 1));
        cities.add(new City(382, "Issaguen Ketama", 1));
        cities.add(new City(383, "Karia El Jadida", 6));
        cities.add(new City(384, "Karia Ba Mohamed", 3));
        cities.add(new City(385, "Oued Amlil", 3));
        cities.add(new City(386, "Oulad Zbair", 3));
        cities.add(new City(387, "Tahla", 3));
        cities.add(new City(388, "Tala Tazegwaght", 1));
        cities.add(new City(389, "Tamassint", 1));
        cities.add(new City(390, "Taounate", 3));
        cities.add(new City(391, "Targuist", 1));
        cities.add(new City(392, "Taza", 3));
        cities.add(new City(393, "Taïnaste", 3));
        cities.add(new City(394, "Thar Es-Souk", 3));
        cities.add(new City(395, "Tissa", 3));
        cities.add(new City(396, "Tizi Ouasli", 3));
        cities.add(new City(397, "Laayounea", 11));
        cities.add(new City(398, "El Marsaa", 11));
        cities.add(new City(399, "Tarfaya", 11));
        cities.add(new City(400, "Boujdour", 11));
        cities.add(new City(401, "Awsard", 12));
        cities.add(new City(402, "Oued-Eddahab", 12));
        cities.add(new City(403, "Stehat", 1));
        cities.add(new City(404, "Aït Attab", 5));
        Log.d(TAG,"Loadind Cities END");

    }
}